<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>OriMod</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Description>Terraria mod that introduces game mechanics and aesthetics based on the Ori series.</Description>
    <RepositoryUrl>https://github.com/Ilemni/OriMod</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
	<ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
	<Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2021.1.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AnimLib\AnimLib.csproj" />
  </ItemGroup>
</Project>